### ISSUE TITLE
Add Starknet Support

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/blink-extension#1]
The extension currently supports only Ethereum and Solana Actions. Add support for Starknet Actions.

Create the Starknet adapter [here](https://github.com/NethermindEth/blink-extension/blob/main/src/adapters). 

Use the Ethereum example as reference.

https://github.com/NethermindEth/blink-extension/blob/main/src/pageScript.js#L5
https://github.com/NethermindEth/blink-extension/blob/main/src/adapters/Ethereum.ts
https://github.com/NethermindEth/blink-extension/blob/main/src/twitterObserver.tsx#L151

The Starknet support will work when

```js
if (actionJson.isStarknet)
```

**Comment by raizo07** [comment]
Hello @jelilat I'll like to work on this

**Comment by BenFaruna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hello, my name is Benjamin Faruna, I am a software engineer with about 3 years of experience. i have experience using python, JavaScript, type script and golang. I am open to learning new things and I would love to handle this issue as an opportunity to learn and grow my interests working with starknetjs.

### How I plan on tackling this issue
1. I will study the other implementations in the repo (Ethereum and solana) and get acquainted with the functions and how they work.
2. Add starknetjs as a dependency to the repo.
3. Implement the functionalities in the order of complexity
4. Test to ensure it works

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hello, my name is Bernal. I am a software developer from Costa Rica. Currently, I work as a back-end developer. In my previous job, I worked as a full-stack developer. Personally, I enjoy developing both the back end and the front end. I have 4 years of experience in the software development industry. Some technologies I have worked with include: Typescript, React, C#, and Node.


### How I plan on tackling this issue
To reach the solution, the first step is to understand how the project works. This involves familiarizing yourself with the project's documentation, structure, and codebase. Next, thoroughly review the issue description to grasp the problem fully. Based on this understanding, brainstorm and propose a viable solution. Once you have a clear plan, implement the solution in the code. After coding, conduct comprehensive tests to ensure the fix resolves the issue without introducing new problems. Finally, review your changes and prepare them for submission, ensuring all aspects of the issue have been addressed effectively.

**Comment by MattCS2006** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
I have worked with **TypeScript** in the past, which would make the process of **building** the adapter for Starknet easier. 

### How I plan on tackling this issue
As a person that likes to **analyze** a lot, I would first check out the **Ethereum and Solana** parts and based on that have an idea on exactly what needs to be done for Starknet. After generating the plan, since I have worked with **TS** before, I would **make the Starknet adapter** using mostly the Ethereum adapter as reference and then **test** that it is working correctly using the **line referenced** at the description of the issue.

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
software engineering background & have contributed in similar projects from previous odhacks

### How I plan on tackling this issue
I understand i'm to create starknet support  and would go through the specified reference to impement this

**Comment by ShantelPeters** [comment]
I will like to work on this issue

```
// src/adapters/Starknet.ts
import { ActionJson } from '../pageScript';

export class StarknetAdapter {
  async getExplorerUrl(actionJson: ActionJson) {
    if (actionJson.isStarknet) {
      const { transactionHash } = actionJson;
      return `(link unavailable);
    }
    return null;
  }

  async getNetworkName(actionJson: ActionJson) {
    if (actionJson.isStarknet) {
      return 'Starknet';
    }
    return null;
  }

  async getChainId(actionJson: ActionJson) {
    if (actionJson.isStarknet) {
      return 534351; // Starknet mainnet chain ID
    }
    return null;
  }
}
```

This adapter provides three methods:

- `getExplorerUrl`: Returns the StarkScan URL for a given transaction hash.
- `getNetworkName`: Returns the name "Starknet" if the action is a Starknet action.
- `getChainId`: Returns the Starknet mainnet chain ID (534351) if the action is a Starknet action.

Note that you'll need to integrate this adapter with the existing codebase, likely in the `pageScript.js` file, and update the `twitterObserver.tsx` file to handle Starknet actions accordingly.

**Comment by sotoyjuan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hey! I'd like to collaborate on this project. I have five years of frontend development experience, including some experience with Solidity, and have been working full-time on a Chrome extension for the past year. Additionally, I am currently going through a Starknet bootcamp, which provides me with the foundational knowledge needed. I believe this combination of my experience and current training makes me well-suited to tackle this issue. Thanks for considering me.

### How I plan on tackling this issue
I will start by studying the existing Ethereum and Solana adapters to understand their structure. Next, I'll create a Starknet adapter using the Ethereum adapter as a reference. I'll integrate and test the new adapter to ensure compatibility.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hello I'm a Web3 dev with extensive knowledge on building on both Ethereum, also contributed to a lot of projects on Starknet.

**Comment by sotoyjuan** [comment]
Happy to help! working on it...

**Comment by jelilat** [comment]
Done in https://github.com/NethermindEth/blink-extension/pull/6
