### ISSUE TITLE
Convert PageScript to Typescript

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/blink-extension#2]
Convert [`PageScript.js`](https://github.com/NethermindEth/blink-extension/blob/main/src/pageScript.js) to `PageScript.ts` and add necessary types

**Comment by Ayoazeez26** [comment]
Hello, can I work on this?

**Comment by juandiegocv27** [comment]
Hi @jelilat, I just comment here to be assigned for this issue, I'll wait to the Od Hack to start in OnlyDust to put my implementation there

**Comment by martinvibes** [comment]
hello @jelilat let me hop on this 
I would like to be a contributor to this repo

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
I'm interested in converting `PageScript.js` to TypeScript for the Blink Extension project. With my 3 years of solid background in JavaScript, TypeScript, and React amd having worked on various browser extension project such `hudddle` screenshare capture etc, I’m confident that I will deliver a robust and type-safe conversion. You can check out my GitHub profile here: [My Github Profile](https://github.com/Benjtalkshow).

### Proposed Solution for Converting `PageScript.js` to TypeScript

## Component Conversion:
- I will convert `src/PageScript.js` to `src/PageScript.ts`.
- I will identify and add necessary TypeScript types and interfaces to ensure type safety and improve code maintainability.

## Type Definitions:
- I will define interfaces for the data structures and functions used within `PageScript.js`.
- I will ensure all function parameters and return types are explicitly typed.

## Code Refactoring:
- I will refactor any parts of the code that can benefit from TypeScript’s features such as enums, type unions, and generics.
- I will update import statements to reflect the TypeScript file extension.
- I will ensure the converted file adheres to the existing linting rules and formatting styles used in the project.
- I will run the project's linter and formatter to maintain consistency.

## Testing and Validation:
- I will thoroughly test the TypeScript version of `PageScript` to ensure it behaves identically to the original JavaScript implementation.
- I will add unit tests for any uncovered parts of the code to ensure robust test coverage.


Looking forward to your feedback and ready to get started on this task!

**Comment by SebastianLF** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
I am a seasoned developer with extensive experience in TypeScript and JavaScript. I have a strong background in developing and maintaining web applications, and I have worked on various projects that involve smart contracts and blockchain technology. My experience with bounties on the Gitcoin platform has honed my skills in quickly understanding and addressing specific issues, collaborating with teams, and delivering high-quality solutions.

### How I plan on tackling this issue
### 1. Understand the Existing Code
- **Read the Code**: I start by reading and understanding the existing code in `PageScript.js`. I identify the functions, variables, objects, and external dependencies.
- **Identify Types**: I note the data types used (strings, numbers, objects, arrays, etc.) and the return types of functions.

### 2. Set Up the TypeScript Environment
- **Install TypeScript**: I ensure that TypeScript is installed in my project. I can install it via npm.
- **Configure tsconfig.json**: I create or update the `tsconfig.json` file to configure the TypeScript compilation options.

### 3. Define the Types
- **Basic Types**: I define the basic types for variables and function parameters.
- **Interfaces and Complex Types**: For complex objects, I define interfaces or types.

### 4. Convert Functions and Variables
- **Rename the File**: I rename `PageScript.js` to `PageScript.ts`.
- **Add Types to Functions**: I add types to the parameters and return values of functions.
- **Type Global Variables**: I add types to global variables.

### 5. Type the Wallet Handlers
- **Define Types for Handlers**: I create interfaces for the wallet connection handlers (`walletHandlers`).
- **Add Types to Functions**: I add types to the functions within `walletHandlers`.

### 6. Type the Message Handlers
- **Define Types for Handlers**: I create interfaces for the message handlers (`messageHandlers`).
- **Add Types to Functions**: I add types to the functions within `messageHandlers`.

### 7. Verify and Correct Errors
- **Compile the Code**: I use the TypeScript compiler to check for type errors.
- **Correct Errors**: I correct the type errors reported by the compiler. This may include adding missing types, correcting incorrect types, and handling `any` types.

### 8. Test the Code
- **Unit Tests**: If unit tests exist, I ensure they pass with the TypeScript code. If not, I write tests to verify that the code functions as expected.
- **Manual Tests**: I perform manual tests to ensure that all functionalities work correctly after the conversion.

### 9. Document the Changes
- **Comments**: I add comments to explain the types and the changes made.
- **Documentation**: I update the project documentation to reflect the changes and the new typing conventions.

### 10. Submit the Changes
- **Commit and Push**: I commit my changes and push them to the repository.
- **Pull Request**: I create a pull request with a detailed description of the changes made and the reasons behind each change.

By following these steps, I can systematically convert `PageScript.js` to `PageScript.ts` while adding the necessary types to improve the robustness and maintainability of the code.

**Comment by ShantelPeters** [comment]
Hello , please can I be assigned to this issue 


_Background and Leverage:_
As a frontend developer with experience in building interactive UI components and API integrations, I'm well-versed in JavaScript and TypeScript, having worked on multiple projects that utilize these technologies

_Approach to the Problem:_

1. _Rename PageScript.js to PageScript.ts:_ I'll start by renaming the file to reflect its new TypeScript nature.
2. _Add Type Annotations:_ I'll add type annotations for variables, function parameters, and return types to ensure code safety and maintainability.
3. _Update Existing Code:_ I'll review the existing code and update it to conform to TypeScript standards and best practices.
4. _Integrate with Existing Codebase:_ I'll ensure the updated PageScript.ts file integrates seamlessly with the existing codebase, including adapters and observers.
5. _Test and Refine:_ I'll thoroughly test the updated code and refine it as needed to ensure it meets the requirements.

_Solution:_
My proposed solution involves renaming the file, adding type annotations, updating existing code, integrating with the existing codebase, and testing and refining the updated code.

_Technical Details:_

- I'll use TypeScript 4.x or later to take advantage of its advanced type features.
- I'll utilize the existing design system and components to maintain consistency.
- I'll ensure the updated code is modular, reusable, and easy to maintain.

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hello, my name is Bernal. I am a software developer from Costa Rica. Currently, I work as a back-end developer. In my previous job, I worked as a full-stack developer. Personally, I enjoy developing both the back end and the front end. I have 4 years of experience in the software development industry. Some technologies I have worked with include: Typescript, React, C#, and Node.


### How I plan on tackling this issue
To reach the solution, the first step is to understand how the project works. This involves familiarizing yourself with the project's documentation, structure, and codebase. Next, thoroughly review the issue description to grasp the problem fully. Based on this understanding, brainstorm and propose a viable solution. Once you have a clear plan, implement the solution in the code. After coding, conduct comprehensive tests to ensure the fix resolves the issue without introducing new problems. Finally, review your changes and prepare them for submission, ensuring all aspects of the issue have been addressed effectively.

**Comment by Benjtalkshow** [comment]
Thanks @jelilat . I will work on this task as soon as possible

**Comment by jelilat** [comment]
This issue has been completed in https://github.com/NethermindEth/blink-extension/commit/0c97c97b364299ae8b3c1776476d9fdbf4f5ee51
