### ISSUE TITLE
Add EVM chain Switch

### ISSUE THREAD

**Issue by jelilat** [NethermindEth/blink-extension#3]
Currently, when connecting to Ethereum, the action connects to any chain the user's wallet is on. Allow the actions builder to first check the current chain, then switch to the expected chain.

```js
await window.ethereum.request({
  "method": "wallet_switchEthereumChain",
  "params": [
    {
      "chainId": "0x2105" // Should vary depending on the chain 
    }
  ]
});
```

Reference 
https://github.com/NethermindEth/blink-extension/blob/main/src/pageScript.js#L6

**Comment by od-hunter** [comment]
I

**Comment by sBaki92** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hi!

I am a freshman in the Starknet ecosystem. I've completed two Basecamps and the latest HackerHouse, and I would like to have this issue assigned to me so I can apply everything I've learned.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/blink-extension).

### My background and how it can be leveraged
Hello @jelilat , can I be assigned this please?
I’m a full stack developer with vast knowledge on html, css, react, JavaScript,TypeScript and solidity and Cairo.

### How I plan on tackling this issue
To solve solve this issue I’ll take the steps below:

First, I’ll verify which chain the user's wallet is currently connected to.
If the wallet is not connected to the expected chain, prompt the user to switch to the correct chain.

Please I would love to be given the opportunity to contribute to this ecosystem.

Here is my Onlydust profile link https://app.onlydust.com/u/od-hunter.

Please give me the opportunity. I’ll be able to come up with a PR within with 2-3 working days once I am assigned.

**Comment by od-hunter** [comment]
Thank you for the opportunity 🙏🏾

**Comment by juandiegocv27** [comment]
Hi @jelilat, 

I'm Juan Diego Carballo, a Full-Stack Web Developer with a keen interest in blockchain technologies. As my first contribution to the Twitter Blink Unfurler project, I am excited to tackle the issue of ensuring the extension connects to the correct Ethereum blockchain.

Proposed Approach:

Chain Identification: I will start by adding a check to see if the user's wallet is on the correct Ethereum chain.
Chain Switching: If the wallet is on a different chain, I will implement the wallet_switchEthereumChain function to request switching to the designated chain (0x2105).
Error Handling: Ensure the extension gracefully handles errors if the chain switch is denied or fails.
I am ready to begin work on this as soon as possible and look forward to contributing effectively to the Twitter Blink Unfurler project.

**Comment by Jemiiah** [comment]
Hello @jelilat this would be my first time on the repository I would love to work on this issue since the current assigned has not created a PR I will create a PR as soon as possible and finish it up with the remaining days before the week run out

**Comment by od-hunter** [comment]
> Hello @jelilat this would be my first time on the repository I would love to work on this issue since the current assigned has not created a PR I will create a PR as soon as possible and finish it up with the remaining days before the week run out

I have created a PR already ser if you had checked well.

**Comment by Jemiiah** [comment]
aiit Hunter

**Comment by Jemiiah** [comment]
@od-hunter  pardon my manners are you still working on this issue

**Comment by jelilat** [comment]
This has been completed in https://github.com/NethermindEth/blink-extension/commit/3714e195e4555a6fd031f6790a073e8776a88f1e

**Comment by Jemiiah** [comment]
okay then @jelilat
